@startuml
skinparam linetype ortho
frame utilities as utilities {
[bounding_boxes] as utilities.bounding_boxes
}
frame utilities as utilities {
[sample_generator] as utilities.sample_generator
}
frame utilities as utilities {
[loss_data] as utilities.loss_data
}
frame unit_tests as unit_tests {
[test_loss_data] as unit_tests.test_loss_data
}
frame unit_tests as unit_tests {
frame networks as unit_tests.networks {
[test_grl] as unit_tests.networks.test_grl
}
}
frame unit_tests as unit_tests {
frame networks as unit_tests.networks {
[test_domain_adaptation_schedules] as unit_tests.networks.test_domain_adaptation_schedules
}
}
frame tracking as tracking {
[trainer] as tracking.trainer
}
frame tracking as tracking {
[run_tracker] as tracking.run_tracker
}
frame tracking as tracking {
[gen_config] as tracking.gen_config
}
frame tracking as tracking {
[tmft] as tracking.tmft
}
frame tracking as tracking {
[data_prov] as tracking.data_prov
}
frame tracking as tracking {
[bbreg] as tracking.bbreg
}
frame modules as modules {
[sample_generator] as modules.sample_generator
}
frame modules as modules {
[training] as modules.training
}
frame modules as modules {
[utils] as modules.utils
}
frame modules as modules {
[model] as modules.model
}
frame experiments as experiments {
[got10k_experiments] as experiments.got10k_experiments
}
frame experiments as experiments {
[command_line] as experiments.command_line
}
frame experiments as experiments {
[pilot_study] as experiments.pilot_study
}
frame experiments as experiments {
[slack_reporter] as experiments.slack_reporter
}
frame networks as networks {
[domain_adaptation_schedules] as networks.domain_adaptation_schedules
}
[utilities.sample_generator] --> [utilities.bounding_boxes]
[unit_tests.test_loss_data] --> [utilities.loss_data]
[unit_tests.networks.test_grl] --> [networks.domain_adaptation_schedules]
[unit_tests.networks.test_domain_adaptation_schedules] --> [networks.domain_adaptation_schedules]
[tracking.run_tracker] --> [tracking.trainer]
[tracking.run_tracker] --> [modules.utils]
[tracking.run_tracker] --> [tracking.data_prov]
[tracking.run_tracker] --> [modules.sample_generator]
[tracking.run_tracker] --> [tracking.bbreg]
[tracking.run_tracker] --> [networks.domain_adaptation_schedules]
[tracking.run_tracker] --> [tracking.gen_config]
[tracking.run_tracker] --> [modules.model]
[tracking.run_tracker] --> [modules.training]
[tracking.tmft] --> [modules.model]
[tracking.tmft] --> [modules.sample_generator]
[tracking.tmft] --> [tracking.run_tracker]
[tracking.tmft] --> [tracking.bbreg]
[tracking.data_prov] --> [modules.utils]
[tracking.bbreg] --> [modules.utils]
[modules.sample_generator] --> [modules.utils]
[modules.model] --> [networks.domain_adaptation_schedules]
[experiments.got10k_experiments] --> [tracking.tmft]
[experiments.got10k_experiments] --> [experiments.command_line]
[experiments.got10k_experiments] --> [experiments.slack_reporter]
[experiments.pilot_study] --> [tracking.gen_config]
[experiments.pilot_study] --> [modules.utils]
[experiments.pilot_study] --> [experiments.command_line]
[experiments.pilot_study] --> [tracking.tmft]
@enduml